name: 将flet 应用打包成 windows 应用

on:
  # 允许从存储库的Actions选项卡 手动 运行此工作流
  workflow_dispatch:

env:
  # flet 官方版本管理 https://flet.dev/docs/publish#versioning
  BUILD_NUMBER: 1
  BUILD_VERSION: 1.0.0

  # Python 版本
  PYTHON_VERSION: 3.12.8

  # 为 "fleet build" 安装的flet -cli版本
  FLET_CLI_VERSION: 0.27.5

  # 使用 UTF-8 编码  
  PYTHONUTF8: 1

  # 在命令行输出中禁用富文本格式
  FLET_CLI_NO_RICH_OUTPUT: 1

  # 使用UV时禁用进度条
  UV_NO_PROGRESS: 1

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install flet-cli ${{ env.FLET_CLI_VERSION }}
      run: |
        python -m pip install --upgrade pip
        pip install flet-cli==$env:FLET_CLI_VERSION

    - name: Flet Build Windows
      run: |
        flet build windows --verbose --no-rich-output --build-number=$env:BUILD_NUMBER --build-version=$env:BUILD_VERSION

    - name: Upload Windows Artifact
      uses: actions/upload-artifact@v4.3.4
      with:
        name: windows-build-artifact
        path: build/windows
        if-no-files-found: error
        overwrite: false
